name: Deploy to Server

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy code to server
        run: |
          sshpass -p "BGT%4rfvcde3" ssh "git_deploy@62.72.57.60" && pwd
