name: Deploy to Server

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server
      run: |
        # Install sshpass
        sudo apt-get update -q
        sudo apt-get install -y sshpass

        # Use the SSH password from GitHub Secrets
        sshpass -p ${{ secrets.SSH_PASSWORD }} ssh git_deploy@62.72.57.60 && pwd
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
